enum AppErrors {
  noErrors,
  images,
  title,
  street,
  buildingName,
  floor,
  apartmentNumber,
  description,
  sizes,
  price,
  tags,
  name,
  phoneInvalid,
  phoneEmpty,
  password,
  pinCodeEmpty,
  pinCodeInvalid,


}

const Map<AppErrors, String> appErrorMessages = {
  AppErrors.noErrors: '',
  AppErrors.street: 'street is required',
  AppErrors.buildingName: 'building Name is required',
  AppErrors.floor: 'floor is required',
  AppErrors.apartmentNumber: 'apartment Number is required',
  AppErrors.images: 'at least provide one image',
  AppErrors.title: 'title is required',
  AppErrors.description: 'description is required',
  AppErrors.tags: 'tags is required',
  AppErrors.price: 'price is required',
  AppErrors.name: 'name is required',
  AppErrors.phoneInvalid: 'invalid phone number',
  AppErrors.phoneEmpty: 'phone is required',
  AppErrors.password: 'password must be at least 8 digits',
  AppErrors.pinCodeEmpty: 'Please Enter Sent Code',
  AppErrors.pinCodeInvalid: 'Pin Code must be 4 numbers',
};
